### ISSUE TITLE
Install and configure Clockify

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2024#1]
Potrebno je napraviti [Clockify](https://clockify.me/) nalog, a zatim instalirati Chrome dodatak za evidenciju vremena unutar GitHub okruženja. Instrukcije se mogu pronaći na sljedećem linku:

https://clockify.me/github-time-tracking

**Kriterijumi prihvatanja:**

- Kreiran nalog i podešeno Clockify okruženje tako da je student registrovan u okviru workspace-a kursa PDS-2024
- Vrijeme se može logovati u GitHub okruženju korišćenjem odgovarajućeg dodatka

**Comment by radislavkosijer** [comment]
Done

**Comment by jelena0000** [comment]
Done.

**Comment by rankomirosav** [comment]
Done

**Comment by Neira7** [comment]
Done.

**Comment by Chicha13** [comment]
Done
