### ISSUE TITLE
Install and configure Git environment

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2024#2]
Potrebno je instalirati i konfigurisati Git okruženje u skladu sa instrukcijama koje su date na glavnoj stranici repozitorijuma (sekcija [Podešavanje Git okruženja za omogućenje pristupa repozitorijumu](https://github.com/etf-unibl/pds-2024/blob/main/docs/git-setup.md)).

**Kriterijumi prihvatanja:**

- Git alat je instaliran što se potvrđuje uspješnim kloniranjem repozitorijuma kursa

**Comment by radislavkosijer** [comment]
Done

**Comment by jelena0000** [comment]
Done.

**Comment by rankomirosav** [comment]
Done

**Comment by Neira7** [comment]
Done.

**Comment by Chicha13** [comment]
Done
