### ISSUE TITLE
Video tutorial (FPGA programming)

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2024#28]
Pogledati video na sljedećem linku:

https://youtu.be/D-kIoQWeO_E

**Kriterijumi prihvatanja:**

- Prezentovani koncepti su potpuno razumljivi
- Dati primjeri su reprodukovani u lokalnom okruženju

**Comment by radislavkosijer** [comment]
Done.

**Comment by jelena0000** [comment]
Done.

**Comment by rankomirosav** [comment]
Done.

**Comment by Neira7** [comment]
Done.

**Comment by Chicha13** [comment]
Done
