### ISSUE TITLE
Get familiar with project workflow in GitHub

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2024#3]
Upoznati se sa [procesom rada u GitHub okruženju](https://github.com/etf-unibl/pds-2024/blob/main/docs/github-workflow.md), kao i sa [pravilima prilikom predavanja rješenja zadataka](https://github.com/etf-unibl/pds-2024/blob/main/docs/git-commit.md). Datim linkovima se može pristupiti i iz glavne stranice u repozitorijumu.

**Comment by rankomirosav** [comment]
Done.

**Comment by Neira7** [comment]
Done.

**Comment by radislavkosijer** [comment]
Done.

**Comment by Chicha13** [comment]
Done
