### ISSUE TITLE
Video tutorial (FPGA basics)

### ISSUE THREAD

**Issue by knezicm** [etf-unibl/pds-2024#4]
Pogledati video na sljedećem linku:

https://youtu.be/oJSAv1hhdgk

**Kriterijumi prihvatanja:**

- Prezentovani koncepti su potpuno razumljivi

**Comment by jelena0000** [comment]
Done.

**Comment by rankomirosav** [comment]
Done.

**Comment by Neira7** [comment]
Done.

**Comment by Chicha13** [comment]
Done

**Comment by radislavkosijer** [comment]
Done.
